[project]
name = "tt12-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "streamlit>=1.52.1",
]

[tool.poetry]
name = "tt12-9"
version = "0.1.0"
package-mode = false
